### ISSUE TITLE
How to copy the selection into system clipboard?

### ISSUE THREAD

**Issue by haifengkao** [b4b4r07/zsh-vi-mode-visual#3]
Is there a way to yank the text into the system clipboard?

I saw the system clipboard setting in 
```bash
set-x-clipboard() {
    if which pbcopy >/dev/null 2>&1; then
        clipcopy='pbcopy'
    elif which xsel >/dev/null 2>&1; then
        clipcopy='xsel --clipboard --input'
    else
        return 1
    fi

    (( ! $+DISPLAY )) ||
        print -rn -- "$1" | eval "$clipcopy"
}
```
But I have no idea about how to enable it.

**Comment by babarot** [comment]
I have fixed to support this feature. Update this plugin and try it out again.

**Comment by haifengkao** [comment]
I just tried it, but it is still not working :(. Could you provide a step-by-step guide?

**Comment by babarot** [comment]
@haifengkao Hmm, sorry... Is the DISPLAY variable set?

**Comment by haifengkao** [comment]
No, how to set it? How to set the variable with plug sign `$+DISPLAY`?

**Comment by babarot** [comment]
Probably this is the cause. I have tried to make it work even if the DISPLAY variable is not set.

**Comment by babarot** [comment]
ref: https://github.com/b4b4r07/zsh-vimode-visual/commit/18273051dc2de614794f185e9c97d351f96c4660

**Comment by ev-agelos** [comment]
I saw in the commit that you either use `xsel` or `pbcopy` as copying wasn't working for me and I realized that I am using `xcip`. Maybe say it in the docs that for the copy to work one of the above 2 tools need to be installed.
